/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AssumptionsRouteImport } from './routes/assumptions'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as HistoricalRouteImport } from './routes/historical'
import { Route as MethodologyRouteImport } from './routes/methodology'
import { Route as ScenariosRouteImport } from './routes/scenarios'
import { Route as SensitivityRouteImport } from './routes/sensitivity'
import { Route as StatementsRouteImport } from './routes/statements'
import { Route as ValidationRouteImport } from './routes/validation'
import { Route as ValuationRouteImport } from './routes/valuation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssumptionsRoute = AssumptionsRouteImport.update({
  id: '/assumptions',
  path: '/assumptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoricalRoute = HistoricalRouteImport.update({
  id: '/historical',
  path: '/historical',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodologyRoute = MethodologyRouteImport.update({
  id: '/methodology',
  path: '/methodology',
  getParentRoute: () => rootRouteImport,
} as any)
const ScenariosRoute = ScenariosRouteImport.update({
  id: '/scenarios',
  path: '/scenarios',
  getParentRoute: () => rootRouteImport,
} as any)
const SensitivityRoute = SensitivityRouteImport.update({
  id: '/sensitivity',
  path: '/sensitivity',
  getParentRoute: () => rootRouteImport,
} as any)
const StatementsRoute = StatementsRouteImport.update({
  id: '/statements',
  path: '/statements',
  getParentRoute: () => rootRouteImport,
} as any)
const ValidationRoute = ValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => rootRouteImport,
} as any)
const ValuationRoute = ValuationRouteImport.update({
  id: '/valuation',
  path: '/valuation',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assumptions': typeof AssumptionsRoute
  '/forecast': typeof ForecastRoute
  '/historical': typeof HistoricalRoute
  '/methodology': typeof MethodologyRoute
  '/scenarios': typeof ScenariosRoute
  '/sensitivity': typeof SensitivityRoute
  '/statements': typeof StatementsRoute
  '/validation': typeof ValidationRoute
  '/valuation': typeof ValuationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assumptions': typeof AssumptionsRoute
  '/forecast': typeof ForecastRoute
  '/historical': typeof HistoricalRoute
  '/methodology': typeof MethodologyRoute
  '/scenarios': typeof ScenariosRoute
  '/sensitivity': typeof SensitivityRoute
  '/statements': typeof StatementsRoute
  '/validation': typeof ValidationRoute
  '/valuation': typeof ValuationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assumptions': typeof AssumptionsRoute
  '/forecast': typeof ForecastRoute
  '/historical': typeof HistoricalRoute
  '/methodology': typeof MethodologyRoute
  '/scenarios': typeof ScenariosRoute
  '/sensitivity': typeof SensitivityRoute
  '/statements': typeof StatementsRoute
  '/validation': typeof ValidationRoute
  '/valuation': typeof ValuationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assumptions'
    | '/forecast'
    | '/historical'
    | '/methodology'
    | '/scenarios'
    | '/sensitivity'
    | '/statements'
    | '/validation'
    | '/valuation'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assumptions'
    | '/forecast'
    | '/historical'
    | '/methodology'
    | '/scenarios'
    | '/sensitivity'
    | '/statements'
    | '/validation'
    | '/valuation'
  id:
    | '__root__'
    | '/'
    | '/assumptions'
    | '/forecast'
    | '/historical'
    | '/methodology'
    | '/scenarios'
    | '/sensitivity'
    | '/statements'
    | '/validation'
    | '/valuation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssumptionsRoute: typeof AssumptionsRoute
  ForecastRoute: typeof ForecastRoute
  HistoricalRoute: typeof HistoricalRoute
  MethodologyRoute: typeof MethodologyRoute
  ScenariosRoute: typeof ScenariosRoute
  SensitivityRoute: typeof SensitivityRoute
  StatementsRoute: typeof StatementsRoute
  ValidationRoute: typeof ValidationRoute
  ValuationRoute: typeof ValuationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assumptions': {
      id: '/assumptions'
      path: '/assumptions'
      fullPath: '/assumptions'
      preLoaderRoute: typeof AssumptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historical': {
      id: '/historical'
      path: '/historical'
      fullPath: '/historical'
      preLoaderRoute: typeof HistoricalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/methodology': {
      id: '/methodology'
      path: '/methodology'
      fullPath: '/methodology'
      preLoaderRoute: typeof MethodologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scenarios': {
      id: '/scenarios'
      path: '/scenarios'
      fullPath: '/scenarios'
      preLoaderRoute: typeof ScenariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensitivity': {
      id: '/sensitivity'
      path: '/sensitivity'
      fullPath: '/sensitivity'
      preLoaderRoute: typeof SensitivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statements': {
      id: '/statements'
      path: '/statements'
      fullPath: '/statements'
      preLoaderRoute: typeof StatementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/validation': {
      id: '/validation'
      path: '/validation'
      fullPath: '/validation'
      preLoaderRoute: typeof ValidationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/valuation': {
      id: '/valuation'
      path: '/valuation'
      fullPath: '/valuation'
      preLoaderRoute: typeof ValuationRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssumptionsRoute: AssumptionsRoute,
  ForecastRoute: ForecastRoute,
  HistoricalRoute: HistoricalRoute,
  MethodologyRoute: MethodologyRoute,
  ScenariosRoute: ScenariosRoute,
  SensitivityRoute: SensitivityRoute,
  StatementsRoute: StatementsRoute,
  ValidationRoute: ValidationRoute,
  ValuationRoute: ValuationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
